#!/bin/bash
cd "$(dirname "$0")"

# Python venv
VENV_DIR="python/venv"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    source "$VENV_DIR/bin/activate"
    pip install pandas matplotlib
else
    source "$VENV_DIR/bin/activate"
fi

# Сборка C++
if [ ! -f build/QAM ]; then
    mkdir -p build && cd build && cmake .. && make && cd ..
fi

build/QAM 4
build/QAM 16
build/QAM 64
python3 python/QAM_Analysis.py
done
